export const ABBREVIATED_TEAM_NAME: { [key: string]: string } = {
  アーセナル: 'ARS',
  アストンヴィラ: 'AVL',
  ウエストハム: 'WHU',
  ウォルバーハンプトン: 'WOL',
  エヴァートン: 'EVE',
  クリスタルパレス: 'CRY',
  サウサンプトン: 'SOU',
  チェルシー: 'CHE',
  トッテナム: 'TOT',
  ニューカッスル: 'NEW',
  ノッティンガムフォレスト: 'NOR',
  ブライトン: 'BHA',
  フラム: 'FLU',
  ブレントフォード: 'BRE',
  ボーンマス: 'BOM',
  マンチェスターシティ: 'MAC',
  マンチェスターユナイテッド: 'MAU',
  リーズ: 'LEE',
  リヴァプール: 'LIV',
  レスター: 'LES'
} as const
